[default]
plan = "nodejs_18, npm-9_x"

[phases]
  [phases.install]
  run = """
    cd backend && npm ci
    cd ../frontend && npm ci
  """

  [phases.build]
  run = """
    cd frontend && npm run build
  """

  [phases.start]
  run = """
    cd backend && node index.js
  """
